In [1]:
import numpy as np

In [ ]:
list =[1,2,3]
list1=[1,2,3]
list2=list*2
print(list1)

[1, 2, 3, 1, 2, 3]


In [7]:
array =np.array(list)

In [9]:
print(type(array))
print(type(list))

<class 'numpy.ndarray'>
<class 'list'>


In [10]:
array2 = array*2
print(array2)

[2 4 6]


In [19]:
array3 = np.array('A')
print(type(array3))
print(array3.ndim)

<class 'numpy.ndarray'>
0


In [29]:
print(array.ndim)

2


In [30]:

array=np.array([[1,2,3],[4,5,6]])

In [27]:
print(array)

[[1, 2, 3], [4, 5, 6]]


In [33]:
td=np.array([[[1,2,3],[4,5,6]],
             [[7,8,9],[10,11,12]],
             [[13,14,15],[16,17,18]]])

In [34]:
print(td.ndim)

3


In [35]:
list=np.array(list)

In [36]:
print(type(list))

<class 'numpy.ndarray'>


In [37]:
list2=list1+list1
print(list2)

[1, 2, 3, 1, 2, 3]


In [38]:
list2=list*2
print(list2)

[2 4 6]


In [40]:
print(list)
list2=list/2
print(list2)

[1 2 3]
[0.5 1.  1.5]


In [41]:
list2 =list-1
print(list2)

[0 1 2]


In [42]:
print(list2)

[0 1 2]


In [44]:
print(list)
print(list.shape)


[1 2 3]
(3,)


In [51]:
print(td)
print(td[2,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
18


In [52]:
print(td[0,0,0]+td[1,0,0]+td[2,0,0])

21


In [53]:
num = td[0,0,0] + td[0,0,1] + td[0,0,2]

In [54]:
print(num)

6


In [ ]:
word=np.array([[['a','b','c'],['d','e','f']]])

In [2]:
array=np.array([[1,2,3],
                [4,5,6],
                [7,8,9],
                [10,11,12],
                [13,14,15],
                [16,17,18]])

In [3]:
array[:,2]=0
print(array)

[[ 1  2  0]
 [ 4  5  0]
 [ 7  8  0]
 [10 11  0]
 [13 14  0]
 [16 17  0]]


In [70]:
print(array[::1])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [111]:
print(array[0:2,1:3:1])

[[2 3]
 [5 6]]


In [ ]:
#array[start:end:step]

In [ ]:
print(array[3,2])
print(array[::1])

12


In [99]:
print(array[:,-2])

[ 2  5  8 11 14 17]


In [105]:
print(array[0,::2])

[1 3]


In [112]:
print(array)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [133]:
newarray =np.array([2,9,16,25])
print(newarray)

[ 2  9 16 25]


In [ ]:
print(newarray +2)
print(newarray - 2)
print(newarray *2)        
print(newarray /2)
print(newarray **2)
print(newarray)
#Check the behavior of the power operator on the array
print(newarray ** newarray)

[ 4 11 18 27]
[ 0  7 14 23]
[ 4 18 32 50]
[ 1.   4.5  8.  12.5]
[  4  81 256 625]
[ 2  9 16 25]
[                   4            387420489                    0
 -6776596920136667815]


In [136]:
print(newarray)
print(np.sqrt(newarray))
print(np.round(np.sqrt(newarray)))


[ 2  9 16 25]
[1.41421356 3.         4.         5.        ]
[1. 3. 4. 5.]


In [145]:
x1=np.array([1,2,3])
x2=np.array([4,5,6])
x3=np.add(x1,x2)
print(x3)
print(np.subtract(x1,x2))
print(np.reciprocal(x3))
    

[5 7 9]
[-3 -3 -3]
[0 0 0]


In [147]:
print(np.pi)

3.141592653589793


In [151]:
radii=np.array([1,2,3])
area=np.multiply(radii**2,np.pi)

In [152]:
print(area)

[ 3.14159265 12.56637061 28.27433388]


In [159]:
score=np.array([85,90,78,92,88])
#print(score.fill(100))
print(score <=60)

[False False False False False]


In [162]:
score [score <=80] = 0
print(score)

[85 90  0 92 88]


In [2]:
arr=np.array([1,2,3])

In [5]:
import math

In [56]:
a.ndim

4

In [61]:
 a=np.array([1,2,3])