In [1]:
import numpy as np

In [2]:
array=np.array([1,2,3,4,5,6,7,8,9,10])

In [13]:
arr2=np.array([[0,0,0,0],[0,0,0,0],[0,0,0,0]])
print(arr2.shape)

(3, 4)


In [14]:
arr=np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
arr1=np.zeros((1,3,4))
print(arr1)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [8]:
iden=np.ones((4,4))
print(iden)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
list=[3, 7, 1, 9, 4]
npar=np.array(list)
print(npar.dtype)
print(npar.ndim)
print(type(npar))

int64
1
<class 'numpy.ndarray'>


In [16]:
arr = np.array([10, 20, 30, 40, 50, 60])
print(arr[1::2])

[20 40 60]


In [17]:
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(mat[1,0:3])

[4 5 6]


In [18]:
print(mat[0:3,2])

[3 6 9]


In [19]:
print(mat[1:3,1:3])

[[5 6]
 [8 9]]


check the difference bw (::-1) and (0:6:-1)

In [27]:
arr1d=np.array([1,2,3,4,5])
print(arr1d[::-1])

[5 4 3 2 1]


In [2]:
import random

In [4]:
ar1d=np.array(random.randint)

In [5]:
print(ar1d)

<bound method Random.randint of <random.Random object at 0x00000154B1E47320>>


In [6]:
print(np.random.rand(3,4))

[[0.44411832 0.61666659 0.12213597 0.70493465]
 [0.86389915 0.09715286 0.11236118 0.58930193]
 [0.79273212 0.34428595 0.56554585 0.35106299]]


In [7]:
print(ar1d.random.rand(3))

AttributeError: 'numpy.ndarray' object has no attribute 'random'

In [17]:
a = np.array([2, 4, 6, 8])
b = np.array([1, 3, 5, 7])
#print(a + b)
#print(a - b)
#print(a * b)
#print(np.round(a / b))
print(a *5)
print(a ** 2)

[10 20 30 40]
[ 4 16 36 64]


In [18]:
arr = np.array([12, 45, 23, 67, 34])


In [19]:
arr.sort()

In [20]:
print(arr)

[12 23 34 45 67]


In [21]:
print(arr.sum())

181


In [22]:
print(arr.mean())
print(arr.max())
print(arr.min())

36.2
67
12


In [23]:
arr = np.array([5, 12, 7, 20, 3, 15])
print(arr > 10)

[False  True False  True False  True]


In [31]:
count=0;
for i in range(len(arr)):
 if(arr [i] > 10):
   count+=1
print(count)

3


Check the below code


In [33]:
#np.count(arr [arr > 10])

In [35]:
x=1
y=10
res='x is greater'if x>y else'y is greater'if y>x else 'both are equal'
print(res)

y is greater


In [ ]:
sum=0
for i in range(101):
    if i%2 !=0:
        continue
    sum+=i
print(sum)

2500
